---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: job-gc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: job-gc
    spec:
      containers:
      - name: job-gc
        image: dubs/k8s-utils:latest
        command:
          - job-gc
        # args:
        #   - "-interval=300"
